name: Docker Image CI

on: [push]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: cd service/ && docker build . --file Dockerfile --tag wezztt/php:static && && docker push wezztt/php:static
